name: Build and Deploy

on:
    workflow_dispatch:

jobs:
    dependency_slave_repository:
        uses: awesomel-es/slave-repository/.github/workflows/main.yml@main
        secrets:
            secret_token: ${{ secrets.GH_TK }}

    build:
        needs: dependency_slave_repository
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            - name: 'Download Artifact'
              uses: actions/download-artifact@v3
              with:
                name: slave-repository
            
            - name: 'Echoing test file'
              run: |
                ls -la
                more test.txt